[functions]
  # Sets a custom directory for Netlify Functions
  directory = "functions/"

  # Specifies `esbuild` for functions bundling
  node_bundler = "esbuild"

  # Flags "package-1" as an external node module for all functions
#   external_node_modules = ["@probot/adapter-aws-lambda-serverless","openai", "probot"]

  # Includes all Markdown files inside the "files/" directory.
  included_files = ["files/*.md"]
